# Generated by Django 4.1.3 on 2022-11-28 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_room_delete_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
