# Generated by Django 4.1.3 on 2022-11-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_room_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='message',
            field=models.ManyToManyField(blank=True, to='chat.message'),
        ),
    ]
